#!/bin/bash
REPODIR=$(git rev-parse --show-toplevel)
SRCDIR=$REPODIR/src

# Find the build directory
BUILDDIR=$(find $REPODIR -name config.h -type f | xargs dirname)

# Use autoconf to generate appropriate ctags
pushd $BUILDDIR &>/dev/null
echo "Building tags..."
make ctags &>/dev/null
popd &>/dev/null

# sed insert, with weird delimiter
INSERT=$'i\\\n'

# Concatenate the generated tag files, sort, fix the headers and output
find $BUILDDIR -name tags -type f \
 | xargs cat \
 | sort \
 | sed -e "1$INSERT!_TAG_FILE_SORTED 1" \
       -e "1$INSERT!_TAG_FILE_FORMAT 2" \
       -e "/^!_/d" \
 > $SRCDIR/tags
